{
 "title": "Power Monitor Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "mac_addr",
    "label": "Device address",
    "query": {
     "query": "SHOW TAG VALUES FROM \"power_telemetry\" WITH KEY = \"mac_addr\""
    }
   },
   {
    "name": "alias",
    "label": "Device name",
    "query": {
     "query": "SELECT DISTINCT(\"device_alias\") FROM \"power_telemetry\" WHERE \"mac_addr\" = '${mac_addr}' ORDER BY time DESC"
    }
   },
   { "name": "power_cost", "label": "Power cost", "query": "0.32450" }
  ]
 },
 "panels": [
  {
   "title": "Last Power Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"power\") AS \"Power Consumption\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Highest Power Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT max(\"power\") AS \"Highest Power Consumption\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Lowest Power Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "SELECT min(\"power\") AS \"Lowest Power Consumption\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT spread(\"total_kwh\") AS \"Total Consumption\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Est. Running Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT spread(\"total_kwh\") * ${power_cost} AS \"Est. Running Cost\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Average Cost per Hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (mean(\"power\") / 1000) * ${power_cost} AS \"Average Cost per Day\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Average Cost per Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (mean(\"power\") / 1000) * ${power_cost} * 24 AS \"Average Cost per Day\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Last Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"voltage\") AS \"Voltage\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Power Consumption",
     "query": "SELECT mean(\"power\") AS \"Power Consumption\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter\nGROUP BY\n  time($__interval)"
    }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Voltage",
     "query": "SELECT mean(\"voltage\") AS \"Voltage\"\nFROM \"power_telemetry\"\nWHERE\n  \"mac_addr\" = '${mac_addr}'\n  AND \"device_alias\" =~ /^${alias}$/\n  AND $timeFilter\nGROUP BY\n  time($__interval*2)"
    }
   ]
  }
 ]
}